version: '3.1'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/
    links:
      - db

  db:
    image: mysql
    container_name: classicmodels2_db
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_DATABASE=classicmodels
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:



# version: "3"

# networks: 
#   app-tier:
#     driver: bridge

# services: 
#   app:
#     build: ./
#     links:
#       -db
#     networks: 
#       - app-tier
#       ports: 
#         - "5000:5000"
#   db:
#     image: mariadb
#     container_name: classicmodels_db
#     ports: 
#       - 3307:3306
#     environment: 
#       - MYSQL_USER=root
#       - MYSQL_ROOT_PASSWORD=root
#       - MYSQL_DATABASE=classicmodels
#     volumes:
#       - ./db:/var/lib/mysql
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     networks: 
#       - app-tier